### ISSUE TITLE
Support Bash shell and environment variables

### ISSUE THREAD

**Issue by guw** [coactions/xvfb#18]
Looking through the docs I wasn't sure if this is possible:
```
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
      ...
      
      - name: Build and Test
        uses: coactions/setup-xvfb@v1
        env:
          BUILD_ID: "..."
          BUILD_TYPE: "..."
          BUILD_LABEL: "..."
        with:
          shell: bash
          run: whatever
```

Is `env` as well as `shell: bash` supported? Especially for Windows this is important because PowerShell does not work [in my case ](https://github.com/bazelbuild/setup-bazelisk/issues/3).
